spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.107:5432/to_do_list_repository
    username: postgres
    password: postgres

server:
  port: 8081

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

connector:
  rest-api:
    url: http://localhost:8080/api



