server:
  port: 8081

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

connector:
  rest-api:
    url: http://localhost:8080/api



